version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: embeddings_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/embeddings_db

  worker:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
    command: celery -A app.tasks worker --loglevel=info
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/embeddings_db
      OLLAMA_BASE_URL: http://host.docker.internal:11434

volumes:
  pgdata:
